# Generated by Django 2.0.6 on 2018-06-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produtos', '0002_auto_20180623_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='Quantidade',
            new_name='quantidade',
        ),
    ]
